/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xampp;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author AMD
 */
public class login extends javax.swing.JFrame {
int attempt = 1;
Connection con=null;
PreparedStatement pst = null;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
     
         jLabel30.setForeground(new Color(51,51,51,0));
         jLabel31.setForeground(new Color(51,51,51,0));
          jLabel32.setForeground(new Color(51,51,51,0));
        jLabel20.setBackground(new Color(51,51,51,200));
        jTextField1.requestFocus();
        jLabel27.setForeground(new Color(255,51,51,0));
         jLabel28.setForeground(new Color(255,51,51,0));
         jLabel22.setVisible(false);
          jLabel6.setVisible(false);
           jLabel25.setVisible(false);
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jLabel33.setVisible(false);
        jSeparator5.setVisible(false);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        jLabel8.setVisible(false);
        jPasswordField2.setVisible(false);
        jLabel11.setVisible(false);
        jLabel18.setVisible(false);
         jLabel16.setVisible(false);
          jLabel17.setVisible(false);
          jLabel26.setVisible(false);
         jLabel9.setVisible(false);
         jLabel19.setVisible(false);
          jLabel33.setVisible(false);
         jLabel35.setVisible(false);
         jLabel36.setVisible(false);
          ImageIcon myimage2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("user.png")));
        Image img5 = myimage2.getImage();
        Image img6 = img5.getScaledInstance(jLabel14.getWidth(),jLabel14.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon c = new ImageIcon(img6);
        jLabel14.setIcon(c);
          ImageIcon myimage3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lock.png")));
        Image img7 = myimage3.getImage();
        Image img8 = img7.getScaledInstance(jLabel15.getWidth(),jLabel15.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon d = new ImageIcon(img8);
        jLabel15.setIcon(d);
           ImageIcon myimage4 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("gmail1.png")));
        Image img9 = myimage4.getImage();
        Image img10 = img9.getScaledInstance(jLabel18.getWidth(),jLabel18.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon e = new ImageIcon(img10);
        jLabel18.setIcon(e);
           ImageIcon myimage5 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("user.png")));
        Image img11 = myimage5.getImage();
        Image img12 = img11.getScaledInstance(jLabel16.getWidth(),jLabel16.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon f = new ImageIcon(img6);
        jLabel16.setIcon(c);
          ImageIcon myimage6 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("lock.png")));
        Image img13 = myimage6.getImage();
        Image img14 = img13.getScaledInstance(jLabel17.getWidth(),jLabel17.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon g = new ImageIcon(img8);
        jLabel17.setIcon(d);
         ImageIcon myimage7 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("2.png")));
        Image img15 = myimage7.getImage();
       
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login And Register System By Andrew Marquez");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 153, 153));
        jLabel33.setText("Password:");
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 140, 20));

        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 153, 153));
        jLabel19.setText("Username:");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 140, 20));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("Gmail:");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 51, 51));
        jLabel30.setText("please enter gmail to register.");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 150, 20));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 51, 51));
        jLabel31.setText("please enter username to register.");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 150, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 51, 51));
        jLabel32.setText("please enter password to register.");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 150, 20));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 153, 153));
        jTextField2.setBorder(null);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 140, 20));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(153, 153, 153));
        jTextField3.setBorder(null);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 140, 20));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 140, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 140, 10));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 140, 10));

        jPasswordField2.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorder(null);
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 140, 20));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTER");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 170, 30));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 30, 30));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 30, 30));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 30, 30));

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("REGISTER");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, -1));

        jLabel11.setBackground(new java.awt.Color(0, 204, 204));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("_________");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 250, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(153, 153, 153));
        jLabel36.setText("Password:");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 20));

        jLabel35.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 153, 153));
        jLabel35.setText("Username:");
        jLabel35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel35MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 20));

        jLabel34.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(153, 153, 153));
        jLabel34.setText("Password:");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 20));

        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 153, 153));
        jLabel23.setText("Username:");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 20));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Login");
        jLabel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22MouseExited(evt);
            }
        });
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 20));

        jPasswordField1.setBackground(new java.awt.Color(51, 51, 51));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 40, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jTextField1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTextField1VetoableChange(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 150, 20));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LOGIN");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 204, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("_______");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 20, 200, 40));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 51, 51));
        jLabel29.setText("please enter Username to login.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 150, 20));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 30, 30));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 30, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("wait            seconds  to login again..");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 51, 51));
        jLabel27.setText("please enter Username to login.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 20));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 51, 51));
        jLabel28.setText("please enter password to login.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 20));

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(204, 204, 204));
        jCheckBox1.setText("Show Password.");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 300));

        jLabel25.setBackground(new java.awt.Color(51, 51, 51));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("LOGIN");
        jLabel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, 50));

        jLabel26.setBackground(new java.awt.Color(51, 51, 51));
        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("REGISTER");
        jLabel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel26.setOpaque(true);
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, 50));

        jLabel24.setBackground(new java.awt.Color(51, 51, 51));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("REGISTER");
        jLabel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 130, 50));

        jLabel3.setBackground(new java.awt.Color(204, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 20, 20));

        jLabel20.setBackground(new java.awt.Color(51, 51, 51));
        jLabel20.setFont(new java.awt.Font("Sitka Banner", 1, 25)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LOGIN AND REGISTER SYSTEM");
        jLabel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel20.setOpaque(true);
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 570, 40));

        jLabel12.setBackground(new java.awt.Color(0, 51, 255));
        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("_");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 20, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xampp/ezgif.com-resize (1).gif"))); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 20));
        jLabel7.setName(""); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   int i = 11;
Timer T=new Timer(1000,new ActionListener()
{public void actionPerformed(ActionEvent e)
{
i--;
jLabel2.setText(""+i);
   if(i == 0){
       T.stop();

 jPasswordField1.setEditable(true);
 jTextField1.setEditable(true);
 jTextField1.requestFocus();
 jLabel22.setVisible(false);
 jLabel26.setVisible(false);
 jLabel2.setText("");
 jLabel6.setVisible(false);
 jLabel24.setVisible(true);
 jLabel35.setVisible(false);
 jLabel36.setVisible(false);
 jLabel34.setVisible(true);
 jLabel23.setVisible(true);
}     
}       
        
});
    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       if(jTextField1.getText().equals("") && jPasswordField1.getText().equals("")){
         jLabel27.setForeground(new Color(255,51,51));
         jLabel28.setForeground(new Color(255,51,51));
          
       }
       else if(!jPasswordField1.equals("") &&jTextField1.getText().equals("")){
         jLabel27.setForeground(new Color(255,51,51));
         jLabel28.setForeground(new Color(255,51,51,0));
        
        }
       else if (jPasswordField1.getText().equals("") && !jTextField1.equals("")){
         jLabel27.setForeground(new Color(255,51,51,0));
         jLabel28.setForeground(new Color(255,51,51));
        }
        

        else{  
            String currentDir=System.getProperty("user.dir");
            
        try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         Connection con = DriverManager.getConnection("jdbc:derby:"+currentDir+"\\info","andrew","andrew");
        String sql = "select * from loginregis where username=? and password=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,jTextField1.getText());
        pst.setString(2,jPasswordField1.getText());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
          JOptionPane.showMessageDialog(this, "login successful!");
         studentinfo info = new studentinfo();
               info.setVisible(true);
               this.setVisible(false);
        }
        else{
        JOptionPane.showMessageDialog(this,"the username or password that u \nentered"
                    + " is incorrect. \n\nATTEMPT:"+attempt,"error",JOptionPane.ERROR_MESSAGE);
         jTextField1.requestFocus();
            if(attempt == 5){
            T.start();
              jTextField1.setText("");
            jTextField1.setEditable(false);
            jPasswordField1.setText(null);
            jLabel22.setVisible(true);
            jLabel4.requestFocus();
             jLabel6.setVisible(true);
             jLabel26.setVisible(true);
             jLabel24.setVisible(false);
             jLabel35.setVisible(true);
             jLabel36.setVisible(true);
             jLabel34.setVisible(false);
             jLabel23.setVisible(false);
            }
            else if(attempt == 10){
            this.dispose();
            }
        }
        con.close();
        
        
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
           attempt++;
        }
       
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
                 jLabel23.move(70,105);
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        // TODO add your handling code here:
         if(jTextField1.getText().equals("")){
         jLabel23.move(70,120);
                  
         }
         
             
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        jTextField1.setForeground(Color.white);
        if(jTextField1.getText().isEmpty()){
        
        }
        else
        {
         jLabel27.setForeground(new Color(255,51,51,0));
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        // TODO add your handling code here:
        jLabel34.move(70,155);
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        // TODO add your handling code here:
         if(jPasswordField1.getText().equals(""))
         {
         jLabel34.move(70,170);
         }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setBackground(Color.white);
        jLabel1.setForeground(Color.black);
      
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         jLabel1.setBackground(Color.black);
        jLabel1.setForeground(Color.white);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        // TODO add your handling code here:
    jLabel9.move(420,165);

    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        // TODO add your handling code here:
         if(jTextField2.getText().equals("")){
         jLabel9.move(420,180);
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        jTextField2.setForeground(Color.white);
         jLabel30.setForeground(new Color(51,51,51,0));
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
        // TODO add your handling code here:
         jLabel19.move(420,215); 
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
        // TODO add your handling code here:
         if(jTextField3.getText().equals(""))
         {
         jLabel19.move(420,230); 
         }
        
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:
        jTextField3.setForeground(Color.white);
         jLabel31.setForeground(new Color(51,51,51,0));
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        // TODO add your handling code here:
          if(jPasswordField2.getText().equals("")){
        jLabel33.move(420,280);
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        // TODO add your handling code here:
     
     jLabel33.move(420,265);
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        try{
            if(jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
        {
        jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51));  
        
        }
         else if(jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
         else if(jTextField2.getText().equals("")  &&
               !jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
         
         else if(!jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
         else if(!jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
          else if(jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
           else if(!jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
         
         
      else{
              if(checkUsername(jTextField3.getText())){
      JOptionPane.showMessageDialog(null, "username already exists!","",JOptionPane.ERROR_MESSAGE);

      } 
      else{
         Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         String currentDir=System.getProperty("user.dir");
          Connection con = DriverManager.getConnection("jdbc:derby:"+currentDir+"\\info","andrew","andrew");
         String sql =  "INSERT INTO loginregis(username,password,gmail) VALUES (?,?,?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,jTextField3.getText());
        pst.setString(2,jPasswordField2.getText());
         pst.setString(3,jTextField2.getText());
        pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "registered!");
      
       int q = this.jPanel1.getX();
        if(q>-1)
        {
            
        Animacion.Animacion.mover_izquierda(340,26,5,5,jPanel1);
        
        //register
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jLabel9.setVisible(false);
         jLabel19.setVisible(false);
          jLabel33.setVisible(false);
        jSeparator5.setVisible(false);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        jLabel8.setVisible(false);
        jPasswordField2.setVisible(false);
        jLabel11.setVisible(false);
        jTextField2.requestFocus();
        jLabel25.setVisible(false);
        jLabel18.setVisible(false);
         jLabel16.setVisible(false);
          jLabel17.setVisible(false);
          jLabel24.setVisible(true);
            jLabel30.setForeground(new Color(51,51,51,0));
         jLabel31.setForeground(new Color(51,51,51,0));
          jLabel32.setForeground(new Color(51,51,51,0));
          
        //login
        jLabel4.setVisible(true);
         jLabel5.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel1.setVisible(true);
      
        jTextField1.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jCheckBox1.setVisible(true);
        jPasswordField1.setText(null);
        jTextField1.setText(null);
         jTextField1.requestFocus();
        }
      jTextField1.requestFocus();
      
      }       
     }
           }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR");
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked
  public boolean checkUsername(String username) throws SQLException{
       PreparedStatement ps = null;
            ResultSet rs;
            boolean checkUser = false;
            String sql = "select * from loginregis where username =?";
         String currentDir=System.getProperty("user.dir");
             Connection con = DriverManager.getConnection("jdbc:derby:"+currentDir+"\\info","andrew","andrew");
        try {
           PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1,jTextField3.getText());
            rs = pst.executeQuery();
            
            if(rs.next()){
            checkUser = true;
            }    
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUser;
        
}
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        jLabel8.setBackground(Color.white);
        jLabel8.setForeground(Color.black);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
         jLabel8.setBackground(Color.black);
        jLabel8.setForeground(Color.white);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         if(jTextField1.getText().equals("") && jPasswordField1.getText().equals("")){
         jLabel27.setForeground(new Color(255,51,51));
         jLabel28.setForeground(new Color(255,51,51));
          
       }
       else if(!jPasswordField1.equals("") &&jTextField1.getText().equals("")){
         jLabel27.setForeground(new Color(255,51,51));
         jLabel28.setForeground(new Color(255,51,51,0));
        
        }
       else if (jPasswordField1.getText().equals("") && !jTextField1.equals("")){
         jLabel27.setForeground(new Color(255,51,51,0));
         jLabel28.setForeground(new Color(255,51,51));
        }
        

        else{  
            String currentDir=System.getProperty("user.dir");
            
        try{
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         Connection con = DriverManager.getConnection("jdbc:derby:"+currentDir+"\\info","andrew","andrew");
        String sql = "select * from loginregis where username=? and password=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,jTextField1.getText());
        pst.setString(2,jPasswordField1.getText());
        ResultSet rs = pst.executeQuery();
        if(rs.next()){
          JOptionPane.showMessageDialog(this, "login successful!");
         studentinfo info = new studentinfo();
               info.setVisible(true);
               this.setVisible(false);
        }
        else{
        JOptionPane.showMessageDialog(this,"the username or password that u \nentered"
                    + " is incorrect. \n\nATTEMPT:"+attempt,"error",JOptionPane.ERROR_MESSAGE);
         jTextField1.requestFocus();
            if(attempt == 5){
            T.start();
              jTextField1.setText("");
            jTextField1.setEditable(false);
            jPasswordField1.setText(null);
            jLabel22.setVisible(true);
            jLabel4.requestFocus();
             jLabel6.setVisible(true);
             jLabel26.setVisible(true);
             jLabel24.setVisible(false);
             jLabel35.setVisible(true);
             jLabel36.setVisible(true);
             jLabel34.setVisible(false);
             jLabel23.setVisible(false);
            }
            else if(attempt == 10){
            this.dispose();
            }
        }
        con.close();
        
        
        
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
           attempt++;
        }
         }
        
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jLabel22MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseExited

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        // TODO add your handling code here:
        jLabel24.setBackground(Color.WHITE);
        jLabel24.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here
         jLabel24.setBackground(Color.DARK_GRAY);
        jLabel24.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel24MouseExited

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
         jLabel25.setBackground(Color.WHITE);
        jLabel25.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        // TODO add your handling code here:
          jLabel25.setBackground(Color.DARK_GRAY);
        jLabel25.setForeground(Color.WHITE);
        
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
        int q = this.jPanel1.getX();
        if(q>-1)
        {
        Animacion.Animacion.mover_izquierda(340,26,5,5,jPanel1);
        //register
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
         jLabel9.setVisible(false);
         jLabel19.setVisible(false);
          jLabel33.setVisible(false);
        jSeparator5.setVisible(false);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        jLabel8.setVisible(false);
        jPasswordField2.setVisible(false);
        jLabel11.setVisible(false);
        jTextField2.requestFocus();
        jLabel25.setVisible(false);
        jLabel18.setVisible(false);
         jLabel16.setVisible(false);
          jLabel17.setVisible(false);
          jLabel24.setVisible(true);
           jLabel30.setForeground(new Color(51,51,51,0));
         jLabel31.setForeground(new Color(51,51,51,0));
          jLabel32.setForeground(new Color(51,51,51,0));
          
        //login
        jLabel4.setVisible(true);
         jLabel5.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel1.setVisible(true);
        jLabel34.setVisible(true);
         jLabel23.setVisible(true);
        jTextField1.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jCheckBox1.setVisible(true);
        jPasswordField1.setText(null);
        jTextField1.setText(null);
         jTextField1.requestFocus();
        }
       
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
       int q = this.jPanel1.getX();
        if(q>-1)
        {
        Animacion.Animacion.mover_derecha(120,340,5,5,jPanel1);
        
        //register
        jLabel10.setVisible(true);
        jTextField2.setVisible(true);
        jTextField3.setVisible(true);
        jLabel33.setVisible(true);
        jSeparator5.setVisible(true);
        jSeparator3.setVisible(true);
        jSeparator4.setVisible(true);
        jLabel8.setVisible(true);
        jPasswordField2.setVisible(true);
        jLabel11.setVisible(true);
        jTextField2.requestFocus();
        jLabel25.setVisible(true);
        jLabel18.setVisible(true);
         jLabel16.setVisible(true);
          jLabel17.setVisible(true);
          jLabel24.setVisible(false);
          jTextField2.setText(null);
           jTextField3.setText(null);
          jPasswordField2.setText(null);
          jTextField3.setForeground(Color.GRAY);
           jLabel9.setVisible(true);
           jLabel19.setVisible(true);
        //login
        jLabel4.setVisible(false);
         jLabel5.setVisible(false);
        jLabel23.setVisible(false);
         jLabel34.setVisible(false);
        jLabel22.setVisible(false);
        jSeparator1.setVisible(false);
        jSeparator2.setVisible(false);
        jPasswordField1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel6.setVisible(false);
       jLabel27.setForeground(new Color(255,51,51,0));
         jLabel28.setForeground(new Color(255,51,51,0));
        jCheckBox1.setVisible(false);
        }
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
        if(jPasswordField1.getText().isEmpty()){
        }
        else
        {
         jLabel28.setForeground(new Color(255,51,51,0));
        }
        
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jTextField1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTextField1VetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1VetoableChange

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyPressed
        // TODO add your handling code here:
         jLabel32.setForeground(new Color(51,51,51,0));
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
try{
            if(jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
        {
        jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51));  
        
        }
         else if(jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
         else if(jTextField2.getText().equals("")  &&
               !jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
         
         else if(!jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
         else if(!jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51)); 
         }
          else if(jTextField2.getText().equals("") &&
               !jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51));
         jLabel31.setForeground(new Color(255,51,51,0));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
           else if(!jTextField2.getText().equals("") &&
               jTextField3.getText().equals("")&&
               !jPasswordField2.getText().equals(""))
         {
          jLabel30.setForeground(new Color(255,51,51,0));
         jLabel31.setForeground(new Color(255,51,51));
          jLabel32.setForeground(new Color(255,51,51,0)); 
         }
         
         
      else{
              if(checkUsername(jTextField3.getText())){
      JOptionPane.showMessageDialog(null, "username already exists!","",JOptionPane.ERROR_MESSAGE);

      } 
      else{
         Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
         String currentDir=System.getProperty("user.dir");
          Connection con = DriverManager.getConnection("jdbc:derby:"+currentDir+"\\info","andrew","andrew");
         String sql =  "INSERT INTO loginregis(username,password,gmail) VALUES (?,?,?)";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1,jTextField3.getText());
        pst.setString(2,jPasswordField2.getText());
         pst.setString(3,jTextField2.getText());
        pst.executeUpdate();
          JOptionPane.showMessageDialog(null, "registered!");
      
       int q = this.jPanel1.getX();
        if(q>-1)
        {
            
        Animacion.Animacion.mover_izquierda(340,26,5,5,jPanel1);
        
        //register
        jLabel10.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jLabel9.setVisible(false);
         jLabel19.setVisible(false);
          jLabel33.setVisible(false);
        jSeparator5.setVisible(false);
        jSeparator3.setVisible(false);
        jSeparator4.setVisible(false);
        jLabel8.setVisible(false);
        jPasswordField2.setVisible(false);
        jLabel11.setVisible(false);
        jTextField2.requestFocus();
        jLabel25.setVisible(false);
        jLabel18.setVisible(false);
         jLabel16.setVisible(false);
          jLabel17.setVisible(false);
          jLabel24.setVisible(true);
            jLabel30.setForeground(new Color(51,51,51,0));
         jLabel31.setForeground(new Color(51,51,51,0));
          jLabel32.setForeground(new Color(51,51,51,0));
          
        //login
        jLabel4.setVisible(true);
         jLabel5.setVisible(true);
        jSeparator1.setVisible(true);
        jSeparator2.setVisible(true);
        jPasswordField1.setVisible(true);
        jLabel1.setVisible(true);
        
        jTextField1.setVisible(true);
        jLabel14.setVisible(true);
        jLabel15.setVisible(true);
        jCheckBox1.setVisible(true);
        jPasswordField1.setText(null);
        jTextField1.setText(null);
         jTextField1.requestFocus();
        }
      jTextField1.requestFocus();
      
      }       
     }
           }catch(Exception e){
        JOptionPane.showMessageDialog(null, "ERROR");
        }    
        }
    }//GEN-LAST:event_jPasswordField2KeyPressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
        {
        jPasswordField1.setEchoChar((char)0);
        }
        else
        {
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseExited

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        jLabel9.move(420,165);
       jTextField2.requestFocus();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
         
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
         jLabel19.move(420,215);
       jTextField3.requestFocus();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
        // TODO add your handling code here:
        jLabel33.move(420,265);
        jPasswordField2.requestFocus();
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        jLabel23.move(70,105);
       jTextField1.requestFocus();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
          jLabel34.move(70,155);
       jPasswordField1.requestFocus();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel35MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         jPasswordField1.requestFocus();
         
         
         }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         jTextField3.requestFocus();
         }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
         jPasswordField2.requestFocus();
         }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
         this.setExtendedState(studentinfo.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
